application:
    openApi:
        baseUrl: http://openapi.airkorea.or.kr/openapi/services/rest
        serviceKey: tPV5y3%2BpRsPBZjxvnpyfghQFqu1OiYenZugPESuPo0V4C51K18Zna9jnApDfXI%2BhtQEmOjz7M8OJxXVbq7VfUg%3D%3D
        version: 1.3
        dataTerm: DAILY
        pageNo: 1
        numOfRows: 10

logging:
    level:
        com.rhyno.misedirty.apis: debug