application:
    openApi:
        baseUrl: http://openapi.airkorea.or.kr/openapi/services/rest
        serviceKey: tPV5y3%2BpRsPBZjxvnpyfghQFqu1OiYenZugPESuPo0V4C51K18Zna9jnApDfXI%2BhtQEmOjz7M8OJxXVbq7VfUg%3D%3D
        version: 1.3
        dataTerm: DAILY
        pageNo: 1
        numOfRows: 10
    criteria:
        pm10:
            level1:
                grade : 1
                start: 0
                end: 15
            level2:
                grade : 2
                start: 16
                end: 30
            level3:
                grade : 3
                start: 31
                end: 40
            level4:
                grade : 4
                start: 41
                end: 50
            level5:
                grade : 5
                start: 51
                end: 75
            level6:
                grade : 6
                start: 76
                end: 100
            level7:
                grade : 7
                start: 101
                end: 150
            level8:
                grade : 8
                start: 151
                end: 999
        pm25:
            level1:
                grade : 1
                start: 0
                end: 8
            level2:
                grade : 2
                start: 9
                end: 15
            level3:
                grade : 3
                start: 16
                end: 20
            level4:
                grade : 4
                start: 21
                end: 25
            level5:
                grade : 5
                start: 26
                end: 37
            level6:
                grade : 6
                start: 38
                end: 50
            level7:
                grade : 7
                start: 51
                end: 75
            level8:
                grade : 8
                start: 76
                end: 999
        so2:
            level1:
                grade : 1
                start: 0
                end: 0.01
            level2:
                grade : 2
                start: 0.01
                end: 0.02
            level3:
                grade : 3
                start: 0.02
                end: 0.04
            level4:
                grade : 4
                start: 0.04
                end: 0.05
            level5:
                grade : 5
                start: 0.05
                end: 0.1
            level6:
                grade : 6
                start: 0.1
                end: 0.15
            level7:
                grade : 7
                start: 0.15
                end: 0.6
            level8:
                grade : 8
                start: 0.6
                end: 999
        co:
            level1:
                grade : 1
                start: 0
                end: 1
            level2:
                grade : 2
                start: 1
                end: 2
            level3:
                grade : 3
                start: 2
                end: 5.5
            level4:
                grade : 4
                start: 5.5
                end: 9
            level5:
                grade : 5
                start: 9
                end: 12
            level6:
                grade : 6
                start: 12
                end: 15
            level7:
                grade : 7
                start: 15
                end: 32
            level8:
                grade : 8
                start: 32
                end: 999
        o3:
            level1:
                grade : 1
                start: 0
                end: 0.02
            level2:
                grade : 2
                start: 0.02
                end: 0.03
            level3:
                grade : 3
                start: 0.03
                end: 0.06
            level4:
                grade : 4
                start: 0.06
                end: 0.09
            level5:
                grade : 5
                start: 0.09
                end: 0.12
            level6:
                grade : 6
                start: 0.12
                end: 0.15
            level7:
                grade : 7
                start: 0.15
                end: 0.38
            level8:
                grade : 8
                start: 0.38
                end: 999
        no2:
            level1:
                grade : 1
                start: 0
                end: 0.02
            level2:
                grade : 2
                start: 0.02
                end: 0.03
            level3:
                grade : 3
                start: 0.03
                end: 0.05
            level4:
                grade : 4
                start: 0.05
                end: 0.06
            level5:
                grade : 5
                start: 0.06
                end: 0.13
            level6:
                grade : 6
                start: 0.13
                end: 0.2
            level7:
                grade : 7
                start: 0.2
                end: 1.1
            level8:
                grade : 8
                start: 1.1
                end: 2

logging:
    level:
        com.rhyno.misedirty.apis: debug